### ISSUE TITLE
Phi size

### ISSUE THREAD

**Issue by zhaoxiaofenfen** [liubenyuan/BSBL-FM#1]
Hello author, 
  I would like to ask what size is the Phi matrix? How to determine the size of Phi if the M and N in your code are unknown?

**Comment by liubenyuan** [comment]
Phi is the sensing matrix which is a random/binary matrix that is pre-generated in CS applications, or it is a dictionary matrix whose columns are the dictionary basis in DOA estimation applications. Its size is known a prior.
