### ISSUE TITLE
刘老师好，请问可以分享一下您博士论文中关于量化压缩感知模型下的贝叶斯算法吗？

### ISSUE THREAD

**Issue by HAPPYBEAR1** [liubenyuan/BSBL-FM#2]
我是做轴承故障检测的，目前用您的BSBL重建算法重建效果很好，非常感激您愿意分享您的研究成果，因为之前的阅读重点是常规压缩的重建算法，今天发现了您论文里还提出的有关量化压缩感知的算法
因为轴承故障信号的特点和您研究的生理信号有很多相似点 最明显的就是稀疏度低，所以冒昧联系您 向您询问是否可以共享相关代码，如果可以的话非常非常非常感谢，代码仅用于学术研究，附上邮箱
wangchao_08042@163.com

**Comment by liubenyuan** [comment]
你好，那部分成果是在科大做的，代码很久远了。我需要找一下。你可能需要自己来实现

**Comment by HAPPYBEAR1** [comment]
谢谢刘老师的回复，您费心了，代码您能找到的话 可以给我发一份嘛



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月07日 16:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [liubenyuan/BSBL-FM] 刘老师好，请问可以分享一下您博士论文中关于量化压缩感知模型下的贝叶斯算法吗？ (Issue #2) |

你好，那部分成果是在科大做的，代码很久远了。我需要找一下。你可能需要自己来实现

**Comment by liubenyuan** [comment]
好的！我找到发你，你留个国内的邮箱

**Comment by HAPPYBEAR1** [comment]
好的好的，谢谢刘老师！！
***@***.******@***.***



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月12日 22:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [liubenyuan/BSBL-FM] 刘老师好，请问可以分享一下您博士论文中关于量化压缩感知模型下的贝叶斯算法吗？ (Issue #2) |

好的！我找到发你，你留个国内的邮箱
